### ISSUE TITLE
Comma missing

### ISSUE THREAD

**Issue by SvsGit** [modhunter/Probably_NOC_Rotations#3]
survival.lua line 48
{ "Explosive Shot", { "player.buff(Lock and Load)", "talent(6,1)", "player.spell(Barrage).cooldown > 1" }}
should be:
{ "Explosive Shot", { "player.buff(Lock and Load)", "talent(6,1)", "player.spell(Barrage).cooldown > 1" }},

**Comment by modhunter** [comment]
Thanks for finding this.  Fixed.
